import {
  DashboardOutlined,
  Inventory2Outlined,
  ShoppingBagOutlined,
  GroupOutlined,
  CurrencyExchangeOutlined,
  ContentPasteOutlined,
  InventoryOutlined,
  PersonOutlineOutlined,
  StarOutlineOutlined,
  NorthEastOutlined,
  AttachMoneyOutlined,
  AccessTimeOutlined,
  CheckCircleOutlineOutlined,
  LocalShippingOutlined,
  HighlightOffOutlined,
} from '@mui/icons-material';

import type {
  IAdminManagedOrderItem,
  IAdminOrderKpiItem,
  IAdminPanelBrandItem,
  IAdminCustomerItem,
  IAdminCustomerKpiItem,
  IAdminPanelLowStockItem,
  IAdminPanelMenuItem,
  IAdminPanelManagedProduct,
  IAdminPanelOrderItem,
  IAdminPanelProductItem,
  IAdminPanelStatItem,
} from '@/core/types';

export const ADMIN_PANEL_MENU: IAdminPanelMenuItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: DashboardOutlined },
  { id: 'product', label: 'Product', icon: Inventory2Outlined, badge: 100 },
  { id: 'orders', label: 'Orders', icon: ShoppingBagOutlined, badge: 10 },
  { id: 'customers', label: 'Customers', icon: GroupOutlined },
];

export const ADMIN_PANEL_STATS: IAdminPanelStatItem[] = [
  {
    id: 'revenue',
    title: 'Total revenue',
    value: 'EUR 120,000',
    subtitle: 'Over the last 30 days',
    trend: '+18.2%',
    isPositive: true,
    icon: CurrencyExchangeOutlined,
  },
  {
    id: 'orders',
    title: 'Total orders',
    value: '1,847',
    subtitle: '124 in processing',
    trend: '+12.5%',
    isPositive: true,
    icon: ContentPasteOutlined,
  },
  {
    id: 'stock',
    title: 'Items in stock',
    value: '3,856',
    subtitle: '12 running low',
    trend: '-3.1%',
    isPositive: false,
    icon: InventoryOutlined,
  },
  {
    id: 'clients',
    title: 'New clients',
    value: '100',
    subtitle: 'This month',
    trend: '+24.8%',
    isPositive: true,
    icon: PersonOutlineOutlined,
  },
];

export const ADMIN_PANEL_BRANDS: IAdminPanelBrandItem[] = [
  { id: 'apple', label: 'Apple', share: 35, color: '#4285f4' },
  { id: 'samsung', label: 'Samsung', share: 28, color: '#8a3ffc' },
  { id: 'xiaomi', label: 'Xiaomi', share: 18, color: '#d930b9' },
  { id: 'google', label: 'Google', share: 12, color: '#eaa60f' },
  { id: 'other', label: 'Other', share: 7, color: '#5f6b83' },
];

export const ADMIN_PANEL_PRODUCTS: IAdminPanelProductItem[] = [
  {
    id: '1',
    title: 'iPhone 15 Pro Max',
    sales: '342 sales - EUR 444,558',
    trend: '+12%',
    stock: '45 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '2',
    title: 'Samsung Galaxy S24 Ultra',
    sales: '298 sales - EUR 357,020',
    trend: '+8%',
    stock: '62 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '3',
    title: 'Google Pixel 8 Pro',
    sales: '187 sales - EUR 186,813',
    trend: '+15%',
    stock: '38 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '4',
    title: 'Xiaomi 14 Pro',
    sales: '156 sales - EUR 132,444',
    trend: '+22%',
    stock: '89 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '5',
    title: 'OnePlus 11',
    sales: '134 sales - EUR 107,066',
    trend: '+5%',
    stock: '54 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '6',
    title: 'Samsung Galaxy S22',
    sales: '342 sales - EUR 444,558',
    trend: '+18%',
    stock: '16 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '7',
    title: 'Honor 90',
    sales: '342 sales - EUR 444,558',
    trend: '+8%',
    stock: '30 pcs',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '8',
    title: 'iPhone 11 128 GB',
    sales: '342 sales - EUR 444,558',
    trend: '+40%',
    stock: '60 pcs',
    image: '/icons/GraySquare.svg',
  },
];

export const ADMIN_PANEL_MANAGED_PRODUCTS: IAdminPanelManagedProduct[] = [
  {
    id: '1',
    title: 'iPhone 15 Pro Max',
    sku: 'IPH-15-PM-256',
    brand: 'Apple',
    price: '$1,299',
    stock: '45 pcs',
    status: 'in_stock',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '2',
    title: 'Samsung Galaxy S24 Ultra',
    sku: 'SAM-S24-U-512',
    brand: 'Samsung',
    price: '$1,199',
    stock: '62 pcs',
    status: 'in_stock',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '3',
    title: 'Google Pixel 8 Pro',
    sku: 'GOO-P8-P-256',
    brand: 'Google',
    price: '$999',
    stock: '38 pcs',
    status: 'in_stock',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '4',
    title: 'Xiaomi 14 Pro',
    sku: 'XIA-14-P-256',
    brand: 'Xiaomi',
    price: '$849',
    stock: '89 pcs',
    status: 'in_stock',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '5',
    title: 'OnePlus 11',
    sku: 'ONE-12-256',
    brand: 'OnePlus',
    price: '$799',
    stock: '54 pcs',
    status: 'in_stock',
    image: '/icons/GraySquare.svg',
  },
  {
    id: '6',
    title: 'iPhone 14',
    sku: 'IPH-14-128',
    brand: 'Apple',
    price: '$699',
    stock: '8 pcs',
    status: 'low_stock',
    image: '/icons/GraySquare.svg',
  },
];

export const ADMIN_PANEL_RECENT_ORDERS: IAdminPanelOrderItem[] = [
  {
    id: '1',
    orderNumber: '#ORD-8472',
    customer: 'John Smith',
    product: 'iPhone 15 Pro',
    age: '5 min',
    status: 'processing',
  },
  {
    id: '2',
    orderNumber: '#ORD-8471',
    customer: 'Maria Johnson',
    product: 'Samsung S24',
    age: '12 min',
    status: 'paid',
  },
  {
    id: '3',
    orderNumber: '#ORD-8470',
    customer: 'Alex Brown',
    product: 'Pixel 8',
    age: '28 min',
    status: 'shipping',
  },
];

export const ADMIN_PANEL_LOW_STOCK: IAdminPanelLowStockItem[] = [
  { id: '1', title: 'iPhone 15 Pro 256GB Black', left: 3, threshold: 10 },
  { id: '2', title: 'Samsung S24 Ultra 512GB Grey', left: 5, threshold: 15 },
  { id: '3', title: 'Google Pixel 8 Pro 128GB White', left: 7, threshold: 12 },
];

export const ADMIN_CUSTOMER_KPIS: IAdminCustomerKpiItem[] = [
  { id: 'total', title: 'Total clients', value: '100', icon: GroupOutlined },
  { id: 'vip', title: 'VIP clients', value: '89', icon: StarOutlineOutlined },
  { id: 'new_month', title: 'New (month)', value: '60', icon: NorthEastOutlined },
  { id: 'receipt', title: 'Wed receipt', value: '$2,200', icon: AttachMoneyOutlined },
];

export const ADMIN_CUSTOMERS: IAdminCustomerItem[] = [
  {
    id: '1',
    name: 'Ivan Petrov',
    email: 'ivan@gmail.com',
    phone: '+380 630000000',
    orders: 12,
    spent: '$8,450',
    registeredAt: 'January 15, 2025',
    status: 'vip',
  },
  {
    id: '2',
    name: 'Maria Ivanova',
    email: 'maria@gmail.com',
    phone: '+380 630000000',
    orders: 8,
    spent: '$5,230',
    registeredAt: 'March 3, 2024',
    status: 'active',
  },
  {
    id: '3',
    name: 'Alex Smirnov',
    email: 'alex@gmail.com',
    phone: '+380 630000000',
    orders: 12,
    spent: '$12,890',
    registeredAt: 'December 22, 2023',
    status: 'vip',
  },
  {
    id: '4',
    name: 'Elena Kozlova',
    email: 'elena@gmail.com',
    phone: '+380 630000000',
    orders: 3,
    spent: '$2,150',
    registeredAt: 'July 10, 2025',
    status: 'new',
  },
  {
    id: '5',
    name: 'Dmitry Volkov',
    email: 'volk@gmail.com',
    phone: '+380 630000000',
    orders: 6,
    spent: '$4,780',
    registeredAt: 'May 5, 2024',
    status: 'active',
  },
];

export const ADMIN_ORDER_KPIS: IAdminOrderKpiItem[] = [
  { id: 'processing', title: 'In processing', value: '23', icon: AccessTimeOutlined },
  { id: 'delivered', title: 'Delivered', value: '856', icon: CheckCircleOutlineOutlined },
  { id: 'delivery', title: 'In delivery', value: '60', icon: LocalShippingOutlined },
  { id: 'cancelled', title: 'Cancelled', value: '23', icon: HighlightOffOutlined },
];

export const ADMIN_MANAGED_ORDERS: IAdminManagedOrderItem[] = [
  {
    id: '1',
    orderNumber: '#ORD-8472',
    customer: 'Ivan Petrov',
    email: 'ivan@gmail.com',
    product: 'iPhone 15 Pro Max',
    quantity: 1,
    amount: '$1,299',
    date: '12 Oct 2025',
    time: '14:30',
    status: 'in_processing',
  },
  {
    id: '2',
    orderNumber: '#ORD-8471',
    customer: 'Maria Ivanova',
    email: 'mari@gmail.com',
    product: 'Samsung Galaxy S24',
    quantity: 1,
    amount: '$999',
    date: '12 Oct 2025',
    time: '13:45',
    status: 'paid',
  },
  {
    id: '3',
    orderNumber: '#ORD-8470',
    customer: 'Alexey Smirov',
    email: 'smir@gmail.com',
    product: 'Google Pixel 8 Pro',
    quantity: 1,
    amount: '$1,998',
    date: '12 Oct 2025',
    time: '11:20',
    status: 'in_delivery',
  },
  {
    id: '4',
    orderNumber: '#ORD-8469',
    customer: 'Elena Kozlova',
    email: 'elen@gmail.com',
    product: 'Xiaomi 14 Pro',
    quantity: 1,
    amount: '$849',
    date: '11 Oct 2025',
    time: '16:15',
    status: 'delivered',
  },
  {
    id: '5',
    orderNumber: '#ORD-8468',
    customer: 'Dmitry Volkov',
    email: 'gima@gmail.com',
    product: 'OnePlus 12',
    quantity: 1,
    amount: '$799',
    date: '11 Oct 2025',
    time: '10:00',
    status: 'cancelled',
  },
  {
    id: '6',
    orderNumber: '#ORD-8467',
    customer: 'Anna Sokolova',
    email: 'anna@gmail.com',
    product: 'iPhone 14',
    quantity: 1,
    amount: '$699',
    date: '11 Oct 2025',
    time: '15:30',
    status: 'paid',
  },
  {
    id: '7',
    orderNumber: '#ORD-8467',
    customer: 'Anna Sokolova',
    email: 'anna@gmail.com',
    product: 'iPhone 14',
    quantity: 1,
    amount: '$699',
    date: '11 Oct 2025',
    time: '15:30',
    status: 'paid',
  },
  {
    id: '8',
    orderNumber: '#ORD-8467',
    customer: 'Anna Sokolova',
    email: 'anna@gmail.com',
    product: 'iPhone 14',
    quantity: 1,
    amount: '$699',
    date: '11 Oct 2025',
    time: '15:30',
    status: 'paid',
  },
  {
    id: '9',
    orderNumber: '#ORD-8467',
    customer: 'Anna Sokolova',
    email: 'anna@gmail.com',
    product: 'iPhone 14',
    quantity: 1,
    amount: '$699',
    date: '11 Oct 2025',
    time: '15:30',
    status: 'paid',
  },
];
