import type { IProduct } from '@/core/types';

import { FALLBACK_IMAGE } from './productMedia';

export const PRODUCTS: IProduct[] = [
  {
    id: 1,
    img: FALLBACK_IMAGE,
    name: 'Apple iPhone 17 Pro Max',
    price: 1300,
    badge: 'Sale',
    inStock: true,
    preOrder: false,
    reviews: 34,
    amount: 1,
  },
  {
    id: 2,
    img: FALLBACK_IMAGE,
    name: 'Samsung Galaxy S22',
    price: 956,
    badge: 'Hit',
    inStock: true,
    preOrder: false,
    reviews: 120,
    amount: 1,
  },
  {
    id: 3,
    img: FALLBACK_IMAGE,
    name: 'Xiaomi 12',
    price: 699,
    inStock: false,
    preOrder: true,
    reviews: 5,
    amount: 1,
  },
  {
    id: 4,
    img: FALLBACK_IMAGE,
    name: 'Apple iPhone 15 Pro',
    price: 1099,
    badge: 'New',
    inStock: true,
    preOrder: false,
    reviews: 210,
    amount: 1,
  },
  {
    id: 5,
    img: FALLBACK_IMAGE,
    name: 'Xiaomi 13 Pro',
    price: 899,
    inStock: true,
    preOrder: false,
    reviews: 78,
    amount: 1,
  },
  {
    id: 6,
    img: FALLBACK_IMAGE,
    name: 'Xiaomi 13T Pro',
    price: 749,
    badge: 'Hit',
    inStock: false,
    preOrder: true,
    reviews: 12,
    amount: 1,
  },
  {
    id: 7,
    img: FALLBACK_IMAGE,
    name: 'OnePlus 11 5G',
    price: 749,
    inStock: true,
    preOrder: false,
    reviews: 44,
    amount: 1,
  },
  {
    id: 8,
    img: FALLBACK_IMAGE,
    name: 'OnePlus Nord 3',
    price: 549,
    badge: 'Sale',
    inStock: true,
    preOrder: false,
    reviews: 3,
    amount: 1,
  },
  {
    id: 9,
    img: FALLBACK_IMAGE,
    name: 'Honor Magic 5 Pro',
    price: 899,
    inStock: true,
    preOrder: false,
    reviews: 89,
    amount: 1,
  },
  {
    id: 10,
    img: FALLBACK_IMAGE,
    name: 'Honor 90',
    price: 499,
    badge: 'New',
    inStock: false,
    preOrder: true,
    reviews: 7,
    amount: 1,
  },
  {
    id: 11,
    img: FALLBACK_IMAGE,
    name: 'Poco F5 Pro',
    price: 1300,
    inStock: true,
    preOrder: false,
    reviews: 256,
    amount: 1,
  },
  {
    id: 12,
    img: FALLBACK_IMAGE,
    name: 'Poco X5 Pro',
    price: 399,
    inStock: false,
    preOrder: true,
    reviews: 6,
    amount: 1,
  },
];
