export const PRODUCTS = [
  {
    id: 1,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 17 Pro Max',
    price: 1300,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 34,
    amount: 1,
  },
  {
    id: 2,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy S22',
    price: 956,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 120,
  },
  {
    id: 3,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 12',
    price: 699,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 5,
  },
  {
    id: 4,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 15 Pro',
    price: 1099,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 210,
  },
  {
    id: 5,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 13 Pro',
    price: 899,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 78,
  },
  {
    id: 6,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 13T Pro',
    price: 749,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 12,
  },
  {
    id: 7,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus 11 5G',
    price: 749,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 44,
  },
  {
    id: 8,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus Nord 3',
    price: 549,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 3,
  },
  {
    id: 9,
    img: '/icons/GraySquare.svg',
    name: 'Honor Magic 5 Pro',
    price: 899,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 89,
  },
  {
    id: 10,
    img: '/icons/GraySquare.svg',
    name: 'Honor 90',
    price: 499,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 7,
  },
  {
    id: 11,
    img: '/icons/GraySquare.svg',
    name: 'Poco F5 Pro',
    price: 1300,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 256,
  },
  {
    id: 12,
    img: '/icons/GraySquare.svg',
    name: 'Poco X5 Pro',
    price: 399,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 6,
  },
  {
    id: 13,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy S23 Ultra',
    price: 1199,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 190,
  },
  {
    id: 14,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 16',
    price: 1099,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 67,
  },
  {
    id: 15,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 14',
    price: 799,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 54,
  },
  {
    id: 16,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus 12',
    price: 699,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 23,
  },
  {
    id: 17,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy Z Fold 5',
    price: 1799,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 299,
  },
  {
    id: 18,
    img: '/icons/GraySquare.svg',
    name: 'Google Pixel 8 Pro',
    price: 999,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 110,
  },
  {
    id: 19,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone SE 4',
    price: 499,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 2,
  },
  {
    id: 20,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi Redmi Note 13',
    price: 349,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 15,
  },
  {
    id: 21,
    img: '/icons/GraySquare.svg',
    name: 'Honor X50',
    price: 399,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 9,
  },
  {
    id: 22,
    img: '/icons/GraySquare.svg',
    name: 'Poco M5',
    price: 299,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 33,
  },
  {
    id: 23,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus Nord CE 3',
    price: 429,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 28,
  },
  {
    id: 24,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy A54',
    price: 499,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 40,
  },
  {
    id: 25,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 14 Plus',
    price: 899,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 77,
  },
  {
    id: 26,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 13 Lite',
    price: 649,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 18,
  },
  {
    id: 27,
    img: '/icons/GraySquare.svg',
    name: 'Google Pixel 7a',
    price: 599,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 125,
  },
  {
    id: 28,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy S21 FE',
    price: 699,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 60,
  },
  {
    id: 29,
    img: '/icons/GraySquare.svg',
    name: 'Honor Magic 4 Lite',
    price: 549,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 11,
  },
  {
    id: 30,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus 10 Pro',
    price: 799,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 95,
  },
  {
    id: 31,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi Mi Mix 5',
    price: 899,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 142,
  },
  {
    id: 32,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 15 Mini',
    price: 799,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 210,
  },
  {
    id: 33,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy Note 23',
    price: 1099,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 65,
  },
  {
    id: 34,
    img: '/icons/GraySquare.svg',
    name: 'Poco F6',
    price: 699,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 47,
  },
  {
    id: 35,
    img: '/icons/GraySquare.svg',
    name: 'Honor 91',
    price: 449,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 29,
  },
  {
    id: 36,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus Nord 4',
    price: 499,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 8,
  },
];
