import type { IProduct } from '@/core/types';
import { FALLBACK_IMAGE } from './productMedia';
import {
  ProductInfoBatteryIcon,
  ProductInfoCameraIcon,
  ProductInfoCoreIcon,
  ProductInfoCpuIcon,
  ProductInfoDeliveryTrackIcon,
  ProductInfoFrontCameraIcon,
  ProductInfoPhoneIcon,
  ProductInfoShopIcon,
  ProductInfoVerifyIcon,
} from '@/assets';

export const PRODUCTS: IProduct[] = [
  {
    id: 1,
    img: FALLBACK_IMAGE,
    name: 'Apple iPhone 17 Pro Max',
    price: 1300,
    badge: 'Sale',
    inStock: true,
    preOrder: false,
    reviews: 34,
    amount: 1,
  },
  {
    id: 2,
    img: FALLBACK_IMAGE,
    name: 'Samsung Galaxy S22',
    price: 956,
    badge: 'Hit',
    inStock: true,
    preOrder: false,
    reviews: 120,
    amount: 1,
  },
  {
    id: 3,
    img: FALLBACK_IMAGE,
    name: 'Xiaomi 12',
    price: 699,
    inStock: false,
    preOrder: true,
    reviews: 5,
    amount: 1,
  },
  {
    id: 4,
    img: FALLBACK_IMAGE,
    name: 'Apple iPhone 15 Pro',
    price: 1099,
    badge: 'New',
    inStock: true,
    preOrder: false,
    reviews: 210,
    amount: 1,
  },
  {
    id: 5,
    img: FALLBACK_IMAGE,
    name: 'Xiaomi 13 Pro',
    price: 899,
    inStock: true,
    preOrder: false,
    reviews: 78,
    amount: 1,
  },
  {
    id: 6,
    img: FALLBACK_IMAGE,
    name: 'Xiaomi 13T Pro',
    price: 749,
    badge: 'Hit',
    inStock: false,
    preOrder: true,
    reviews: 12,
    amount: 1,
  },
  {
    id: 7,
    img: FALLBACK_IMAGE,
    name: 'OnePlus 11 5G',
    price: 749,
    inStock: true,
    preOrder: false,
    reviews: 44,
    amount: 1,
  },
  {
    id: 8,
    img: FALLBACK_IMAGE,
    name: 'OnePlus Nord 3',
    price: 549,
    badge: 'Sale',
    inStock: true,
    preOrder: false,
    reviews: 3,
    amount: 1,
  },
  {
    id: 9,
    img: FALLBACK_IMAGE,
    name: 'Honor Magic 5 Pro',
    price: 899,
    inStock: true,
    preOrder: false,
    reviews: 89,
    amount: 1,
  },
  {
    id: 10,
    img: FALLBACK_IMAGE,
    name: 'Honor 90',
    price: 499,
    badge: 'New',
    inStock: false,
    preOrder: true,
    reviews: 7,
    amount: 1,
  },
  {
    id: 11,
    img: FALLBACK_IMAGE,
    name: 'Poco F5 Pro',
    price: 1300,
    inStock: true,
    preOrder: false,
    reviews: 256,
    amount: 1,
  },
  {
    id: 12,
    img: FALLBACK_IMAGE,
    name: 'Poco X5 Pro',
    price: 399,
    inStock: false,
    preOrder: true,
    reviews: 6,
    amount: 1,
  },
];

export const PRODUCT_GALLERY_IMAGES = [
  {
    id: 1,
    src: '/icons/productImg/SmallFirst.svg',
    alt: 'Second Image',
  },
  {
    id: 2,
    src: '/icons/productImg/SmallSecond.svg',
    alt: 'Third Image',
  },
  {
    id: 3,
    src: '/icons/productImg/SmallThird.svg',
    alt: 'Fourth Image',
  },
  {
    id: 4,
    src: '/icons/productImg/SmallFourth.svg',
    alt: 'Fifth Image',
  },
];

export const PRODUCT_SPECS_META = [
  {
    id: 1,
    label: 'Screen Size',
    icon: ProductInfoPhoneIcon,
    alt: 'Screen icon',
  },
  {
    id: 2,
    label: 'CPU',
    icon: ProductInfoCpuIcon,
    alt: 'CPU icon',
  },
  {
    id: 3,
    label: 'Cores',
    icon: ProductInfoCoreIcon,
    alt: 'Core icon',
  },
  {
    id: 4,
    label: 'Main camera',
    icon: ProductInfoCameraIcon,
    alt: 'Camera icon',
  },
  {
    id: 5,
    label: 'Front camera',
    icon: ProductInfoFrontCameraIcon,
    alt: 'Front-camera icon',
  },
  {
    id: 6,
    label: 'Battery',
    icon: ProductInfoBatteryIcon,
    alt: 'Battery icon',
  },
] as const;

export const SPECS = [
  {
    id: 1,
    label: 'Screen Size',
    value: '6.7',
    icon: ProductInfoPhoneIcon,
    alt: 'Screen icon',
  },
  {
    id: 2,
    label: 'CPU',
    value: 'Samsung',
    icon: ProductInfoCpuIcon,
    alt: 'CPU icon',
  },
  {
    id: 3,
    label: 'Cores',
    value: '6',
    icon: ProductInfoCoreIcon,
    alt: 'Core icon',
  },
  {
    id: 4,
    label: 'Main camera',
    value: '48-12-12 MP',
    icon: ProductInfoCameraIcon,
    alt: 'Camera icon',
  },
  {
    id: 5,
    label: 'Front camera',
    value: '12 MP',
    icon: ProductInfoFrontCameraIcon,
    alt: 'Front-camera icon',
  },
  {
    id: 6,
    label: 'Battery',
    value: '4323 mAh',
    icon: ProductInfoBatteryIcon,
    alt: 'Battery icon',
  },
];

export const PRODUCT_META = [
  {
    id: 1,
    label: 'Delivery',
    value: '1-2 day',
    icon: ProductInfoDeliveryTrackIcon,
    alt: 'Delivery Icon',
  },
  {
    id: 2,
    label: 'In Stock',
    value: 'Today',
    icon: ProductInfoShopIcon,
    alt: 'Shop Icon',
  },
  {
    id: 3,
    label: 'Guaranteed',
    value: '1 year',
    icon: ProductInfoVerifyIcon,
    alt: 'Guaranteed Icon',
  },
];
