export const PRODUCTS = [
  {
    id: 1,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 17 Pro Max',
    price: 1300,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 34,
    amount: 1,
  },
  {
    id: 2,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy S22',
    price: 956,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 120,
    amount: 1,
  },
  {
    id: 3,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 12',
    price: 699,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 5,
    amount: 1,
  },
  {
    id: 4,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 15 Pro',
    price: 1099,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 210,
    amount: 1,
  },
  {
    id: 5,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 13 Pro',
    price: 899,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 78,
    amount: 1,
  },
  {
    id: 6,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 13T Pro',
    price: 749,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 12,
    amount: 1,
  },
  {
    id: 7,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus 11 5G',
    price: 749,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 44,
    amount: 1,
  },
  {
    id: 8,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus Nord 3',
    price: 549,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 3,
    amount: 1,
  },
  {
    id: 9,
    img: '/icons/GraySquare.svg',
    name: 'Honor Magic 5 Pro',
    price: 899,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 89,
    amount: 1,
  },
  {
    id: 10,
    img: '/icons/GraySquare.svg',
    name: 'Honor 90',
    price: 499,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 7,
    amount: 1,
  },
  {
    id: 11,
    img: '/icons/GraySquare.svg',
    name: 'Poco F5 Pro',
    price: 1300,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 256,
    amount: 1,
  },
  {
    id: 12,
    img: '/icons/GraySquare.svg',
    name: 'Poco X5 Pro',
    price: 399,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 6,
    amount: 1,
  },
  {
    id: 13,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy S23 Ultra',
    price: 1199,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 190,
    amount: 1,
  },
  {
    id: 14,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 16',
    price: 1099,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 67,
    amount: 1,
  },
  {
    id: 15,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 14',
    price: 799,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 54,
    amount: 1,
  },
  {
    id: 16,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus 12',
    price: 699,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 23,
    amount: 1,
  },
  {
    id: 17,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy Z Fold 5',
    price: 1799,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 299,
    amount: 1,
  },
  {
    id: 18,
    img: '/icons/GraySquare.svg',
    name: 'Google Pixel 8 Pro',
    price: 999,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 110,
    amount: 1,
  },
  {
    id: 19,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone SE 4',
    price: 499,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 2,
    amount: 1,
  },
  {
    id: 20,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi Redmi Note 13',
    price: 349,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 15,
    amount: 1,
  },
  {
    id: 21,
    img: '/icons/GraySquare.svg',
    name: 'Honor X50',
    price: 399,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 9,
    amount: 1,
  },
  {
    id: 22,
    img: '/icons/GraySquare.svg',
    name: 'Poco M5',
    price: 299,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 33,
    amount: 1,
  },
  {
    id: 23,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus Nord CE 3',
    price: 429,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 28,
    amount: 1,
  },
  {
    id: 24,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy A54',
    price: 499,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 40,
    amount: 1,
  },
  {
    id: 25,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 14 Plus',
    price: 899,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 77,
    amount: 1,
  },
  {
    id: 26,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi 13 Lite',
    price: 649,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 18,
    amount: 1,
  },
  {
    id: 27,
    img: '/icons/GraySquare.svg',
    name: 'Google Pixel 7a',
    price: 599,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 125,
    amount: 1,
  },
  {
    id: 28,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy S21 FE',
    price: 699,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 60,
    amount: 1,
  },
  {
    id: 29,
    img: '/icons/GraySquare.svg',
    name: 'Honor Magic 4 Lite',
    price: 549,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 11,
    amount: 1,
  },
  {
    id: 30,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus 10 Pro',
    price: 799,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: false,
    preOrder: true,
    reviews: 95,
    amount: 1,
  },
  {
    id: 31,
    img: '/icons/GraySquare.svg',
    name: 'Xiaomi Mi Mix 5',
    price: 899,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 142,
    amount: 1,
  },
  {
    id: 32,
    img: '/icons/GraySquare.svg',
    name: 'Apple iPhone 15 Mini',
    price: 799,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 210,
    amount: 1,
  },
  {
    id: 33,
    img: '/icons/GraySquare.svg',
    name: 'Samsung Galaxy Note 23',
    price: 1099,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 65,
    amount: 1,
  },
  {
    id: 34,
    img: '/icons/GraySquare.svg',
    name: 'Poco F6',
    price: 699,
    sale: false,
    hit: true,
    newProduct: false,
    inStock: false,
    preOrder: true,
    reviews: 47,
    amount: 1,
  },
  {
    id: 35,
    img: '/icons/GraySquare.svg',
    name: 'Honor 91',
    price: 449,
    sale: false,
    hit: false,
    newProduct: true,
    inStock: true,
    preOrder: false,
    reviews: 29,
    amount: 1,
  },
  {
    id: 36,
    img: '/icons/GraySquare.svg',
    name: 'OnePlus Nord 4',
    price: 499,
    sale: true,
    hit: false,
    newProduct: false,
    inStock: true,
    preOrder: false,
    reviews: 8,
    amount: 1,
  },
];

export const PRODUCT_GALLERY_IMAGES = [
  {
    id: 1,
    src: '/icons/productImg/SmallFirst.svg',
    alt: 'Second Image',
  },
  {
    id: 2,
    src: '/icons/productImg/SmallSecond.svg',
    alt: 'Third Image',
  },
  {
    id: 3,
    src: '/icons/productImg/SmallThird.svg',
    alt: 'Fourth Image',
  },
  {
    id: 4,
    src: '/icons/productImg/SmallFourth.svg',
    alt: 'Fivth Image',
  },
];

export const SPECS = [
  {
    id: 1,
    label: 'Screen Size',
    value: '6.7',
    icon: '/icons/ProductInfoIcons/phone.svg',
    alt: 'Screen icon',
  },
  {
    id: 2,
    label: 'CPU',
    value: 'Samsung',
    icon: '/icons/ProductInfoIcons/CPU.svg',
    alt: 'CPU icon',
  },
  { id: 3, label: 'Cores', value: '6', icon: '/icons/ProductInfoIcons/core.svg', alt: 'Core icon' },
  {
    id: 4,
    label: 'Main camera',
    value: '48-12-12 MP',
    icon: '/icons/ProductInfoIcons/camera.svg',
    alt: 'Camera icon',
  },
  {
    id: 5,
    label: 'Front camera',
    value: '12 MP',
    icon: '/icons/ProductInfoIcons/frontCamera.svg',
    alt: 'Front-camera icon',
  },
  {
    id: 6,
    label: 'Battery',
    value: '4323 mAh',
    icon: '/icons/ProductInfoIcons/battery.svg',
    alt: 'Battery icon',
  },
];

export const PRODUCT_META = [
  {
    id: 1,
    label: 'Delivery',
    value: '1-2 day',
    icon: '/icons/ProductInfoIcons/deliveryTrack.svg',
    alt: 'Delivery Icon',
  },
  {
    id: 2,
    label: 'In Stock',
    value: 'Today',
    icon: '/icons/ProductInfoIcons/shop.svg',
    alt: 'Shop Icon',
  },
  {
    id: 3,
    label: 'Guaranteed',
    value: '1 year',
    icon: '/icons/ProductInfoIcons/verify.svg',
    alt: 'Guaranteed Icon',
  },
];
